### ISSUE TITLE
Custom Art for Elaphaea Icon & Background

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Elaphaea#19]
- [x] Favicon
  - [ ] Traditionally Favicons are 16 x 16, but you can start at 32 x 32 then save two versions
  - [ ] The favicon should not have square corners, either make it a circle or rounded since sharp corners usually dont look good, see below... Unless you guys can make it work
  - [ ] ![Image](https://user-images.githubusercontent.com/85896950/189942098-03f0a3d6-a783-4e34-b51a-f0d56611e7c5.png)
  
  
  - [ ] ![Image](https://user-images.githubusercontent.com/85896950/189942000-f92edad7-d10e-4673-91e9-c1235850e136.png)
- [x] The BACKGROUND image exported from Figma is 1440px wide
     - [ ] ![Image](https://user-images.githubusercontent.com/85896950/189952396-ad7d9fb7-3c4c-4d62-b82c-7c66552611cc.png)
     - [ ] Although we can stretch it with css, an image that is at least 1920 x 1080 pixels would be optimal

**Comment by kaymiika** [comment]
FIXED :D
-Favicon uploaded
-Higher res / cleaner text vector uploaded for login page
-higher res deer BG image uploaded, changed to grayscale with backdrop-filter for now
